name: Publish Site

on:
  workflow_dispatch:
  push:
    branches:
     - main

env:
  QUARTO_DIR: "."

jobs:
  publish:
    name: Build & Deploy Quarto Project
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/insightsengineering/rstudio:latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Staged dependencies
        uses: insightsengineering/staged-dependencies-action@v2
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: "."
          enable-check: false
          direction: upstream

      - name: Render Quarto Project
        run: quarto render --output-dir _site
        shell: bash
        working-directory: ${{ env.QUARTO_DIR }}
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Project to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.QUARTO_DIR }}/_site
          destination_dir: ${{ env.QUARTO_DIR }}