name: Publish Site

on:
  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  publish:
    name: Build & Deploy Quarto Project
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/insightsengineering/rstudio:latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Staged dependencies
        uses: insightsengineering/staged-dependencies-action@v2
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: "."
          enable-check: false
          direction: upstream

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
